# Form implementation generated from reading ui file 'main_1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1428, 763)
        MainWindow.setMinimumSize(QtCore.QSize(700, 300))
        MainWindow.setStyleSheet("/* =========================================\n"
"   全局基础设置 (清晰易读的深灰字体)\n"
"========================================= */\n"
"* {\n"
"    font-family: \"Microsoft YaHei\", \"Segoe UI\", sans-serif;\n"
"    font-size: 13px;\n"
"    color: #333333; /* 主字体颜色：深灰，比纯黑柔和 */\n"
"}\n"
"\n"
"/* 主窗口背景色 (非常浅的灰白色，减少视觉疲劳) */\n"
"QMainWindow, #centralwidget {\n"
"    background-color: #F0F2F5; \n"
"}\n"
"\n"
"/* 菜单栏 */\n"
"QMenuBar {\n"
"    background-color: #FFFFFF;\n"
"    border-bottom: 1px solid #D9D9D9;\n"
"}\n"
"QMenuBar::item:selected {\n"
"    background-color: #E6F7FF;\n"
"    color: #005FB8;\n"
"}\n"
"\n"
"/* =========================================\n"
"   一级栏目标题 (title_1 到 title_5)\n"
"   样式：浅蓝底色 + 沉稳深蓝左侧边条\n"
"========================================= */\n"
"QLabel[objectName^=\"title_\"] {\n"
"    background-color: #E6F0FA; \n"
"    color: #005A9E; /* 沉稳的专业蓝 */\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 6px 10px; /* 减小内边距，防止字被挤压 */\n"
"    border-left: 4px solid #005A9E;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"/* =========================================\n"
"   优化后：功能区的二级小标题 (块状标签风格)\n"
"========================================= */\n"
"QLabel[text=\"图像真实性鉴定\"], QLabel[text=\"图像处理\"] {\n"
"    background-color: #F0F4F8; /* 极浅的灰蓝色背景 */\n"
"    color: #005A9E; /* 沉稳蓝文字，呼应顶部主标题 */\n"
"    font-weight: bold;\n"
"    padding: 8px 12px; /* 增加内边距，撑起高度 */\n"
"    border-radius: 6px; /* 更圆润的边角 */\n"
"    margin-top: 15px; /* 与上方的元素拉开呼吸空间 */\n"
"    margin-bottom: 5px; /* 与下方的首个按钮保持微小距离 */\n"
"}\n"
"\n"
"/* =========================================\n"
"   优化后：功能按钮 (现代扁平侧边栏风格)\n"
"========================================= */\n"
"QPushButton {\n"
"    background-color: transparent; /* 默认透明，与大背景融为一体 */\n"
"    border: 1px solid transparent; /* 透明边框占位，防止悬停时控件跳动 */\n"
"    border-radius: 6px;\n"
"    padding: 8px 15px;\n"
"    color: #4A4A4A; /* 深灰文字，不刺眼 */\n"
"    text-align: left; /* 【关键】文字靠左，为前面的图标留出整齐的空间 */\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"/* 悬停状态 (Hover) - 浮现底色，文字变亮蓝 */\n"
"QPushButton:hover {\n"
"    background-color: #FFFFFF; /* 悬停时凸显为白色卡片 */\n"
"    border: 1px solid #E0E4E8; /* 细微的边框勾勒 */\n"
"    color: #1890FF; /* 文字亮起，提供强烈的交互暗示 */\n"
"}\n"
"\n"
"/* 按下状态 (Pressed) - 物理按压反馈 */\n"
"QPushButton:pressed {\n"
"    background-color: #E6F0FA; /* 按下时变为更深的蓝色底 */\n"
"    color: #005A9E;\n"
"    /* 【高级细节】下面两行通过改变内边距，模拟按钮被真实按下去的物理下沉感 */\n"
"    padding-top: 10px; \n"
"    padding-left: 17px; \n"
"} /*=========================================\n"
"   检材区 (虚线上传框)\n"
"========================================= */\n"
"QLabel[objectName^=\"box_\"] {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px dashed #C0C0C0; /* 灰色虚线 */\n"
"    border-radius: 6px;\n"
"    color: #999999; \n"
"    font-size: 24px; /* 加号放大 */\n"
"}\n"
"\n"
"QLabel[objectName^=\"box_\"]:hover {\n"
"    border: 1px dashed #1890FF;\n"
"    background-color: #F0F7FF;\n"
"    color: #1890FF; /* 悬停变蓝，暗示可交互 */\n"
"}\n"
"\n"
"/* =========================================\n"
"   图像与文本显示区 (纯白面板)\n"
"========================================= */\n"
"QLabel#img_evidence, QLabel#img_result, QTextEdit, QListWidget {\n"
"    background-color: #FFFFFF; /* 纯白画布 */\n"
"    border: 1px solid #D9D9D9; /* 清晰的浅灰边框，划定界限 */\n"
"    border-radius: 4px;\n"
"    color: #999999; /* 占位文字颜色 */\n"
"}\n"
"\n"
"QTextEdit, QListWidget {\n"
"    color: #333333; /* 实际输入的文字为深色 */\n"
"}\n"
"\n"
"/* =========================================\n"
"   精美的滑块 (Slider)\n"
"========================================= */\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #D9D9D9;\n"
"    background: #F0F0F0;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #1890FF; /* 走过的进度条为蓝色 */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #FFFFFF;\n"
"    border: 2px solid #1890FF;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"/* =========================================\n"
"   进度条 (ProgressBar)\n"
"========================================= */\n"
"QProgressBar {\n"
"    background-color: #F0F0F0;\n"
"    border: 1px solid #D9D9D9;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #1890FF;\n"
"    border-radius: 3px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.title_1 = QtWidgets.QLabel(parent=self.widget)
        self.title_1.setGeometry(QtCore.QRect(0, 0, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_1.sizePolicy().hasHeightForWidth())
        self.title_1.setSizePolicy(sizePolicy)
        self.title_1.setMinimumSize(QtCore.QSize(0, 0))
        self.title_1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.title_1.setObjectName("title_1")
        self.box_2 = QtWidgets.QLabel(parent=self.widget)
        self.box_2.setGeometry(QtCore.QRect(0, 160, 110, 110))
        self.box_2.setMinimumSize(QtCore.QSize(0, 0))
        self.box_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.box_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.box_2.setObjectName("box_2")
        self.box_4 = QtWidgets.QLabel(parent=self.widget)
        self.box_4.setGeometry(QtCore.QRect(0, 400, 110, 110))
        self.box_4.setMinimumSize(QtCore.QSize(0, 0))
        self.box_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.box_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.box_4.setObjectName("box_4")
        self.box_5 = QtWidgets.QLabel(parent=self.widget)
        self.box_5.setGeometry(QtCore.QRect(0, 520, 110, 110))
        self.box_5.setMinimumSize(QtCore.QSize(0, 0))
        self.box_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.box_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.box_5.setObjectName("box_5")
        self.box_1 = QtWidgets.QLabel(parent=self.widget)
        self.box_1.setGeometry(QtCore.QRect(0, 40, 110, 110))
        self.box_1.setMinimumSize(QtCore.QSize(0, 0))
        self.box_1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.box_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.box_1.setObjectName("box_1")
        self.box_3 = QtWidgets.QLabel(parent=self.widget)
        self.box_3.setGeometry(QtCore.QRect(0, 280, 110, 110))
        self.box_3.setMinimumSize(QtCore.QSize(0, 0))
        self.box_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.box_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.box_3.setObjectName("box_3")
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 500, 165, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 540, 165, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 170, 165, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(0, 370, 165, 54))
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_9.setObjectName("label_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 580, 165, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 420, 165, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 250, 165, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 90, 165, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 130, 165, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_2.setObjectName("pushButton_2")
        self.title_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.title_2.setGeometry(QtCore.QRect(0, 0, 165, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_2.sizePolicy().hasHeightForWidth())
        self.title_2.setSizePolicy(sizePolicy)
        self.title_2.setMinimumSize(QtCore.QSize(0, 0))
        self.title_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.title_2.setObjectName("title_2")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 210, 165, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 460, 165, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(0, 40, 165, 54))
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.label_12 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_12.setGeometry(QtCore.QRect(0, 420, 370, 30))
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_12.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_12.setObjectName("label_12")
        self.horizontalSlider = QtWidgets.QSlider(parent=self.widget_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(0, 460, 370, 10))
        self.horizontalSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.img_evidence = QtWidgets.QLabel(parent=self.widget_3)
        self.img_evidence.setGeometry(QtCore.QRect(0, 40, 370, 370))
        self.img_evidence.setMinimumSize(QtCore.QSize(0, 0))
        self.img_evidence.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.img_evidence.setText("")
        self.img_evidence.setObjectName("img_evidence")
        self.title_3 = QtWidgets.QLabel(parent=self.widget_3)
        self.title_3.setGeometry(QtCore.QRect(0, 0, 370, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_3.sizePolicy().hasHeightForWidth())
        self.title_3.setSizePolicy(sizePolicy)
        self.title_3.setMinimumSize(QtCore.QSize(0, 0))
        self.title_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.title_3.setObjectName("title_3")
        self.label_13 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_13.setGeometry(QtCore.QRect(0, 500, 370, 30))
        self.label_13.setMinimumSize(QtCore.QSize(0, 0))
        self.label_13.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_13.setObjectName("label_13")
        self.progressBar = QtWidgets.QProgressBar(parent=self.widget_3)
        self.progressBar.setGeometry(QtCore.QRect(0, 550, 370, 10))
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.img_result = QtWidgets.QLabel(parent=self.widget_4)
        self.img_result.setGeometry(QtCore.QRect(0, 40, 370, 370))
        self.img_result.setMinimumSize(QtCore.QSize(370, 370))
        self.img_result.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.img_result.setText("")
        self.img_result.setObjectName("img_result")
        self.title_4 = QtWidgets.QLabel(parent=self.widget_4)
        self.title_4.setGeometry(QtCore.QRect(0, 0, 370, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_4.sizePolicy().hasHeightForWidth())
        self.title_4.setSizePolicy(sizePolicy)
        self.title_4.setMinimumSize(QtCore.QSize(370, 18))
        self.title_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.title_4.setObjectName("title_4")
        self.txt_info = QtWidgets.QTextEdit(parent=self.widget_4)
        self.txt_info.setGeometry(QtCore.QRect(0, 420, 371, 241))
        self.txt_info.setMinimumSize(QtCore.QSize(0, 0))
        self.txt_info.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.txt_info.setObjectName("txt_info")
        self.horizontalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_5.setObjectName("widget_5")
        self.title_5 = QtWidgets.QLabel(parent=self.widget_5)
        self.title_5.setGeometry(QtCore.QRect(0, 0, 165, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_5.sizePolicy().hasHeightForWidth())
        self.title_5.setSizePolicy(sizePolicy)
        self.title_5.setMinimumSize(QtCore.QSize(0, 0))
        self.title_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.title_5.setObjectName("title_5")
        self.list_history = QtWidgets.QListWidget(parent=self.widget_5)
        self.list_history.setGeometry(QtCore.QRect(0, 40, 165, 621))
        self.list_history.setMinimumSize(QtCore.QSize(0, 0))
        self.list_history.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.list_history.setObjectName("list_history")
        self.horizontalLayout.addWidget(self.widget_5)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 7)
        self.horizontalLayout.setStretch(3, 7)
        self.horizontalLayout.setStretch(4, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1428, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.RightToolBarArea, self.toolBar_3)
        self.toolBar_4 = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar_4.setObjectName("toolBar_4")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar_4)
        self.action_1 = QtGui.QAction(parent=MainWindow)
        self.action_1.setObjectName("action_1")
        self.action_2 = QtGui.QAction(parent=MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtGui.QAction(parent=MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action_1)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数字图像真实性鉴定系统"))
        self.title_1.setText(_translate("MainWindow", "      检材区"))
        self.box_2.setText(_translate("MainWindow", "+"))
        self.box_4.setText(_translate("MainWindow", "+"))
        self.box_5.setText(_translate("MainWindow", "+"))
        self.box_1.setText(_translate("MainWindow", "+"))
        self.box_3.setText(_translate("MainWindow", "+"))
        self.pushButton_8.setText(_translate("MainWindow", "图像去模糊"))
        self.pushButton_9.setText(_translate("MainWindow", "图像去噪"))
        self.pushButton_3.setText(_translate("MainWindow", "颜色直方图"))
        self.label_9.setText(_translate("MainWindow", "图像处理"))
        self.pushButton_10.setText(_translate("MainWindow", "去雨/雪/雾"))
        self.pushButton_6.setText(_translate("MainWindow", "图像修复"))
        self.pushButton_5.setText(_translate("MainWindow", "篡改鉴定及定位"))
        self.pushButton.setText(_translate("MainWindow", "图像基本信息"))
        self.pushButton_2.setText(_translate("MainWindow", "DCT直方图"))
        self.title_2.setText(_translate("MainWindow", "功能区"))
        self.pushButton_4.setText(_translate("MainWindow", "生成式图像检测"))
        self.pushButton_7.setText(_translate("MainWindow", "超分辨率"))
        self.label_8.setText(_translate("MainWindow", "图像真实性鉴定"))
        self.label_12.setText(_translate("MainWindow", "默认置信度：0.6"))
        self.title_3.setText(_translate("MainWindow", "证据图像"))
        self.label_13.setText(_translate("MainWindow", "实时进度条"))
        self.title_4.setText(_translate("MainWindow", "结果图像"))
        self.title_5.setText(_translate("MainWindow", "历史操作记录"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "退出"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
        self.toolBar_4.setWindowTitle(_translate("MainWindow", "toolBar_4"))
        self.action_1.setText(_translate("MainWindow", "打开"))
        self.action_2.setText(_translate("MainWindow", "导出结果图像"))
        self.action_3.setText(_translate("MainWindow", "导出历史记录"))
